#!/usr/bin/env node
// Generates site/index.html — a listing of every file in site/ except the
// index page itself and dotfiles. Run automatically by the GitHub Pages
// workflow on each deploy, so adding a cheatsheet never requires editing the
// index by hand. You can also run it locally to preview: `node scripts/build-index.mjs`.

import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, extname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const siteDir = resolve(__dirname, "..", "site");

// Files that are never listed, regardless of where they live.
const EXCLUDED = new Set(["index.html", "readme.md", "license"]);

const HTML_EXTS = new Set([".html", ".htm"]);

const ENTITIES = {
  "&amp;": "&",
  "&lt;": "<",
  "&gt;": ">",
  "&quot;": '"',
  "&#39;": "'",
  "&apos;": "'",
  "&mdash;": "—",
  "&ndash;": "–",
};

function decodeEntities(str) {
  return str.replace(/&[a-z#0-9]+;/gi, (m) => ENTITIES[m.toLowerCase()] ?? m);
}

function escapeHtml(str) {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function titleCase(str) {
  return str.replace(/\b\w/g, (c) => c.toUpperCase());
}

function humanSize(bytes) {
  if (bytes < 1024) return `${bytes} B`;
  const units = ["KB", "MB", "GB"];
  let value = bytes / 1024;
  let unit = 0;
  while (value >= 1024 && unit < units.length - 1) {
    value /= 1024;
    unit += 1;
  }
  return `${value.toFixed(value < 10 ? 1 : 0)} ${units[unit]}`;
}

// Pull the first matching capture out of some HTML, or return null.
function firstMatch(html, regex) {
  const m = html.match(regex);
  return m ? m[1].trim() : null;
}

function extractMeta(html, name) {
  const re = new RegExp(
    `<meta[^>]*name=["']${name}["'][^>]*content=["']([^"']*)["']`,
    "i",
  );
  const alt = new RegExp(
    `<meta[^>]*content=["']([^"']*)["'][^>]*name=["']${name}["']`,
    "i",
  );
  return firstMatch(html, re) ?? firstMatch(html, alt);
}

// Split "Name — Tagline" style titles into their two halves.
function splitTitle(title) {
  const separators = [" — ", " – ", " | ", " - ", "—", "–"];
  for (const sep of separators) {
    const idx = title.indexOf(sep);
    if (idx > 0) {
      return {
        name: title.slice(0, idx).trim(),
        tagline: title.slice(idx + sep.length).trim(),
      };
    }
  }
  return { name: title.trim(), tagline: null };
}

function describe(fileName) {
  const ext = extname(fileName).toLowerCase();
  const stats = statSync(join(siteDir, fileName));
  const base = { file: fileName, size: humanSize(stats.size), type: (ext.slice(1) || "file").toUpperCase() };

  if (HTML_EXTS.has(ext)) {
    const html = readFileSync(join(siteDir, fileName), "utf8");
    const rawTitle = firstMatch(html, /<title[^>]*>([\s\S]*?)<\/title>/i);
    const description = extractMeta(html, "description");
    if (rawTitle) {
      const { name, tagline } = splitTitle(decodeEntities(rawTitle));
      return { ...base, name, tagline: description ?? tagline };
    }
  }

  // Fallback: derive a readable name from the file name.
  const stem = fileName.replace(/\.[^.]+$/, "").replace(/[-_]+/g, " ");
  return { ...base, name: titleCase(stem), tagline: null };
}

const entries = readdirSync(siteDir)
  .filter((name) => !name.startsWith("."))
  .filter((name) => !EXCLUDED.has(name.toLowerCase()))
  .filter((name) => statSync(join(siteDir, name)).isFile())
  .map(describe)
  .sort((a, b) => a.name.localeCompare(b.name));

const cards =
  entries.length === 0
    ? `      <p class="empty">No cheatsheets yet. Drop an <code>.html</code> file into <code>site/</code> and it will appear here.</p>`
    : entries
        .map((entry) => {
          const tagline = entry.tagline
            ? `\n          <p class="card-tagline">${escapeHtml(entry.tagline)}</p>`
            : "";
          return `      <li>
        <a class="card" href="./${escapeHtml(entry.file)}">
          <div class="card-head">
            <h2 class="card-title">${escapeHtml(entry.name)}</h2>
            <span class="badge">${escapeHtml(entry.type)}</span>
          </div>${tagline}
          <p class="card-meta"><code>${escapeHtml(entry.file)}</code><span class="dot">&middot;</span>${escapeHtml(entry.size)}</p>
        </a>
      </li>`;
        })
        .join("\n");

const count = entries.length;
const countLabel = `${count} ${count === 1 ? "cheatsheet" : "cheatsheets"}`;

const html = `<!DOCTYPE html>
<!-- Auto-generated by scripts/build-index.mjs. Do not edit by hand; edit the script instead. -->
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Cheatsheets — Clean, printable developer references</title>
<meta name="description" content="A growing collection of clean, printable developer cheatsheets.">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;700&display=swap" rel="stylesheet">
<style>
  :root{
    --bg:#ffffff;
    --surface:#f6f8fa;
    --surface-hover:#eef1f4;
    --ink:#0d1117;
    --ink-soft:#57606a;
    --line:#d0d7de;
    --accent:#0969da;
    --accent-soft:#ddf4ff;
    --badge-bg:#eaeef2;
    --badge-ink:#424a53;
    --mono:'JetBrains Mono', ui-monospace, 'SFMono-Regular', Menlo, Consolas, monospace;
    --sans:'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
  }
  @media (prefers-color-scheme: dark){
    :root{
      --bg:#0d1117;
      --surface:#161b22;
      --surface-hover:#1c232c;
      --ink:#e6edf3;
      --ink-soft:#8b949e;
      --line:#30363d;
      --accent:#4493f8;
      --accent-soft:#132132;
      --badge-bg:#21262d;
      --badge-ink:#adbac7;
    }
  }

  *{box-sizing:border-box;}
  html{scroll-behavior:smooth;}
  body{
    margin:0;
    background:var(--bg);
    color:var(--ink);
    font-family:var(--sans);
    font-size:16px;
    line-height:1.6;
    -webkit-font-smoothing:antialiased;
  }
  ::selection{background:var(--accent-soft);}
  a{color:var(--accent); text-decoration:none;}
  a:hover{text-decoration:underline;}
  code{font-family:var(--mono); font-size:0.85em;}

  .topbar{height:4px; background:linear-gradient(90deg,var(--accent),#54aeff,var(--accent));}

  header.masthead{
    max-width:900px; margin:0 auto; padding:3.5rem 1.5rem 1.5rem;
  }
  .masthead h1{
    font-family:var(--mono); font-weight:700; font-size:2.1rem;
    margin:0; letter-spacing:-0.02em;
  }
  .masthead p{
    margin:0.6rem 0 0; font-size:1.05rem; color:var(--ink-soft); max-width:40rem;
  }
  .masthead .count{
    display:inline-block; margin-top:1.25rem;
    font-family:var(--mono); font-size:0.78rem; font-weight:500;
    color:var(--ink-soft); background:var(--surface);
    border:1px solid var(--line); border-radius:999px; padding:0.25rem 0.75rem;
  }

  main{max-width:900px; margin:0 auto; padding:1rem 1.5rem 4rem;}
  ul.cards{list-style:none; margin:0; padding:0; display:grid; gap:1rem;}
  @media (min-width:620px){ ul.cards{grid-template-columns:1fr 1fr;} }

  .card{
    display:block; height:100%;
    background:var(--surface); border:1px solid var(--line); border-radius:12px;
    padding:1.25rem 1.35rem; color:inherit;
    transition:border-color .15s ease, transform .15s ease, background .15s ease;
  }
  .card:hover{
    text-decoration:none; border-color:var(--accent);
    background:var(--surface-hover); transform:translateY(-2px);
  }
  .card-head{display:flex; align-items:center; justify-content:space-between; gap:0.75rem;}
  .card-title{font-size:1.15rem; font-weight:600; margin:0; letter-spacing:-0.01em;}
  .badge{
    flex:none; font-family:var(--mono); font-size:0.65rem; font-weight:700;
    letter-spacing:0.05em; color:var(--badge-ink); background:var(--badge-bg);
    border-radius:5px; padding:0.2rem 0.45rem;
  }
  .card-tagline{margin:0.5rem 0 0; font-size:0.92rem; color:var(--ink-soft);}
  .card-meta{
    margin:0.9rem 0 0; font-size:0.78rem; color:var(--ink-soft);
    display:flex; align-items:center; gap:0.5rem;
  }
  .card-meta .dot{opacity:0.6;}
  .empty{color:var(--ink-soft); font-size:1rem;}

  footer{
    max-width:900px; margin:0 auto; padding:2rem 1.5rem 3rem;
    border-top:1px solid var(--line);
    font-size:0.85rem; color:var(--ink-soft);
    display:flex; flex-wrap:wrap; gap:0.5rem 1.25rem; align-items:center;
  }
</style>
</head>
<body>
<div class="topbar"></div>
<header class="masthead">
  <h1>Cheatsheets</h1>
  <p>A growing collection of clean, printable developer references. Pick one below.</p>
  <span class="count">${countLabel}</span>
</header>
<main>
  <ul class="cards">
${cards}
  </ul>
</main>
<footer>
  <span>&copy; Michal Ferber</span>
  <a href="https://github.com/MichalAFerber/cheatsheets">Source on GitHub</a>
  <a href="https://github.com/MichalAFerber/cheatsheets/blob/main/LICENSE">MIT License</a>
</footer>
</body>
</html>
`;

writeFileSync(join(siteDir, "index.html"), html);
console.log(`Generated site/index.html with ${count} entr${count === 1 ? "y" : "ies"}.`);
